export const RPV_MAX_N = 500;
export const MESSAGE_RETENTION_DAYS = 30;
export const RPV_GROUP_COOLDOWN_SECONDS = 30;
export const RPV_USER_COOLDOWN_SECONDS = 60;
export const SOULS_MAX_CHARS = 1500;
export const QUESTION_MAX_CHARS = 400;
export const QUESTION_CONTEXT_MESSAGES = 300;
