const PHRASES = [
  "🐒 ¡Ooh ooh ah ah! Arrancando el tractor…",
  "🍌 Un momento, el mono está calentando motores…",
  "🚜 Brrrrum brrrrum… acelerando neuronas…",
  "🐵 Plátano cargado, generando imagen…",
  "🌾 El mono ya está en el campo, sed pacientes…",
  "🛞 Pisando el embrague de la creatividad…",
  "🔧 Apretando tuercas con los pies, esto va a salir bien…",
  "💭 Pensando como un mono que conduce un tractor…",
  "🐒 Iiiik iiiik! ¡Aquí viene la obra maestra!",
  "☁️ Convocando al espíritu del mono granjero…",
  "🎨 Mezclando pintura con la cola del mono…",
  "🪖 Misión recibida, mono al volante…",
  "🪴 Sembrando píxeles, recogeremos imagen…",
  "🥁 Redoble de tambores… el mono está enfocado…",
  "🍌 Plátano + diesel = magia, espera…",
  "🐒 Aupa! Que viene el mono campesino…",
  "🏎️ El tractor del mono se ha puesto modo turbo…",
  "🤲 Las manos del mono ya están en el volante…",
  "🥥 El mono ha terminado el desayuno, ahora a trabajar…",
  "🌽 Cargando maíz creativo en el silo del cerebro…",
  "📻 Sintonizando Radio Mono FM, esperad el cuadro…",
  "🎭 El mono se está poniendo en personaje, drama inminente…",
  "🪕 Ajustando las cuerdas del banjo antes del retrato…",
  "🧠 El cerebro del mono trabaja a 200 RPM ahora mismo…",
  "🛠️ Garaje del mono abierto, soldando píxeles…",
  "🦍 Ha llegado el mono pintor, todos quietos…",
  "🚜💨 Olor a gasoil y a obra de arte, esperad…",
  "🥕 El mono cambió plátano por zanahoria, está raro hoy…",
  "🎬 Acción! Cámara! Mono! …vale, casi vale…",
  "🌪️ El mono se está concentrando, no respiréis…",
  "🦜 El loro copiloto está dando instrucciones inútiles…",
  "🍍 Surreal mode activado, agarraos al asiento…",
  "🛻 El tractor ha pedido un café antes de salir…",
  "🪩 El mono está bailando en la cabina, no juzguemos…",
  "🐂 Carga pesada, el mono lo va a hacer igual…",
  "🦓 Hoy el mono está experimentando con rayas…",
  "🌶️ Picante extra en el prompt, prepárate…",
  "🛰️ Coordenadas recibidas, el mono va a la zona creativa…",
  "🐝 Las abejas están ayudando al mono a decidir el estilo…",
  "🪂 El mono ha saltado al lienzo en paracaídas…",
  "🦴 Excavando una obra maestra del fango…",
  "🎪 Mono al volante, espectáculo asegurado…",
  "🧃 Zumo de plátano cargado al máximo, generando…",
  "🐠 El mono está pescando inspiración en el río…",
  "🎲 Tirando los dados del destino visual…",
  "🪐 El mono se ha ido a otro planeta, esperad imagen…",
  "🦔 El erizo asistente del mono está confundido pero feliz…",
];

export function pickMonkeyPhrase(rng: () => number = Math.random): string {
  const value = PHRASES[Math.floor(rng() * PHRASES.length)];
  if (value === undefined) {
    throw new Error("pickMonkeyPhrase: empty pool");
  }
  return value;
}
