const STYLES = [
  "vintage 1970s film photograph",
  "Studio Ghibli watercolor",
  "Pixar 3D render",
  "oil painting in the style of a Dutch master",
  "black-and-white wood engraving",
  "Saturday morning cartoon",
  "low-poly PS1 graphics",
  "claymation still",
  "Renaissance fresco",
  "synthwave neon poster",
  "pencil sketch from a field naturalist's notebook",
  "Soviet propaganda poster",
  "Polaroid snapshot",
  "Wes Anderson symmetrical wide shot",
  "Hayao Miyazaki concept art",
  "Lego brick diorama",
  "cyberpunk anime cel",
  "watercolor children's book illustration",
  "stained-glass window panel",
  "comic book panel with halftone shading",
  "Banksy stencil graffiti",
  "Art Nouveau poster in the style of Mucha",
  "Norman Rockwell magazine cover",
  "Soviet constructivist poster",
  "ukiyo-e woodblock print",
  "1990s VHS box art",
  "Edward Hopper oil painting",
  "Hieronymus Bosch surrealist panel",
  "Salvador Dalí dreamscape",
  "art deco travel poster",
  "Mexican muralist mural in the style of Diego Rivera",
  "1960s pulp sci-fi paperback cover",
  "Pixar concept-art turnaround sheet",
  "Aardman stop-motion still",
  "Tim Burton gothic illustration",
  "Moebius bande-dessinée panel",
  "Persian miniature painting",
  "Andy Warhol pop-art silkscreen",
  "high-fashion editorial photograph for Vogue",
  "National Geographic wildlife photograph",
  "1980s Lisa Frank holographic sticker",
  "graphite charcoal sketch with smudges",
  "Roy Lichtenstein dotted comic panel",
  "Bayeux Tapestry embroidery panel",
  "vaporwave aesthetic with grid floor",
  "isometric pixel art",
  "infrared thermal-vision rendering",
  "macro tilt-shift miniature photograph",
  "fisheye GoPro action shot",
  "anatomical engraving from a 19th-century encyclopedia",
  "blueprint schematic with annotations",
  "shadow-puppet silhouette on rice paper",
  "neon-noir cyberpunk illustration in the style of Syd Mead",
  "1970s Saul Bass minimalist poster",
  "Margaret Keane big-eyes painting",
  "Frida Kahlo self-portrait style",
  "M.C. Escher impossible-geometry print",
  "Hayao Miyazaki dramatic widescreen frame",
  "Bob Ross happy-trees oil painting",
  "early IBM technical illustration",
];

const TRACTORS = [
  "rusty red tractor",
  "shiny green John Deere",
  "tiny toy tractor",
  "enormous monster-truck tractor",
  "antique steam-powered tractor",
  "futuristic levitating tractor",
  "wooden hand-carved tractor",
  "neon-lit tractor with chrome exhausts",
  "muddy farm tractor pulling a plow",
  "tractor with comically oversized wheels",
  "tractor made entirely of bananas",
  "tractor built from LEGO bricks",
  "tractor covered in flowers and vines",
  "miniature go-kart-sized tractor",
  "tractor pulling a trailer full of pineapples",
  "tractor decorated like a parade float",
  "tractor that looks like a giant croissant",
  "armored military-surplus tractor",
  "solar-panel-covered eco-tractor",
  "rust-bucket tractor with one wheel missing",
  "Formula-1-style racing tractor",
  "submarine tractor with portholes",
  "tractor made of glowing crystals",
  "tractor with caterpillar tank treads",
  "art-deco brass-and-copper tractor",
  "tractor disguised as a giant pumpkin",
  "tractor with rocket boosters strapped on",
  "bamboo-and-rope handmade tractor",
  "tractor with a barn welded on top",
  "low-rider tractor with hydraulics",
];

const SETTINGS = [
  "in a golden wheat field at sunset",
  "on a muddy jungle trail",
  "rolling through a snowy Alpine pass",
  "in the middle of a busy city intersection",
  "on the surface of the Moon",
  "in an Italian vineyard at dawn",
  "down a cobblestone European village street",
  "across a Martian desert with two suns",
  "through a flooded rice paddy",
  "on a beach with crashing waves behind",
  "in a flower-filled mountain meadow",
  "deep in a misty redwood forest",
  "on top of a tall grassy hill",
  "in a thunderstorm with lightning behind",
  "through autumn leaves on a country lane",
  "across a salt flat reflecting the sky",
  "down the middle of Times Square",
  "through the canals of Venice",
  "on the Great Wall of China",
  "at the foot of an active volcano",
  "in a glowing bioluminescent forest",
  "on a sandy desert dune at noon",
  "through a Tokyo neon back-alley",
  "at the edge of the Grand Canyon",
  "in an underwater coral garden",
  "across a frozen Arctic ice field",
  "through a Saharan sandstorm",
  "on a pirate-ship deck mid-sea",
  "in a floating sky-island village",
  "down the Champs-Élysées on Bastille Day",
  "on a baseball diamond mid-game",
  "in the middle of a music festival crowd",
  "through a haunted graveyard at midnight",
  "on a rooftop helipad in Dubai",
  "at the bottom of a dried-up riverbed",
  "in a candy-colored fairy-tale village",
  "across a battlefield from a medieval painting",
  "in an abandoned amusement park",
  "through a field of giant sunflowers taller than the tractor",
  "on the rings of Saturn",
];

const MONKEY_QUIRKS = [
  "wearing aviator sunglasses",
  "smoking a corncob pipe",
  "with a tiny straw cowboy hat",
  "drinking from a coconut",
  "wearing overalls and chewing on wheat",
  "sporting a beret and a tiny mustache",
  "with a baby monkey co-pilot",
  "wearing a racing helmet",
  "holding a baguette",
  "with a parrot on its shoulder",
  "wearing a tuxedo",
  "with sunglasses and a gold chain",
  "wearing a wizard's robe and pointy hat",
  "dressed as a sushi chef with a headband",
  "wearing scuba gear with goggles on its forehead",
  "in a full astronaut suit with the helmet off",
  "wearing a flamenco dress",
  "in samurai armor",
  "wearing a banana costume",
  "dressed as a 1920s flapper",
  "in a chef's whites holding a wooden spoon",
  "wearing a Hawaiian shirt and floral lei",
  "dressed as a Renaissance painter with palette",
  "in lederhosen with a feathered cap",
  "wearing a NASA jumpsuit",
  "dressed as a clown with a red nose",
  "wearing a kilt and tartan sash",
  "in a tiny crown and royal robe",
  "wearing a hi-vis vest and hard hat",
  "dressed as a pirate with eye patch",
  "wearing a 1970s leisure suit",
  "in a karate gi with a black belt",
  "wearing a snorkel and flippers",
  "dressed as a wizard's apprentice with star-spangled cape",
  "in a doctor's lab coat with stethoscope",
];

const MOODS = [
  "looking extremely smug",
  "with a determined expression",
  "laughing maniacally",
  "looking serene and zen-like",
  "with intense focus",
  "looking utterly bewildered",
  "with a heroic, triumphant pose",
  "looking like it's about to drop a sick beat",
  "with the wide-eyed wonder of a child",
  "in deep philosophical contemplation",
  "with the swagger of a rock star",
  "looking suspicious of the camera",
  "with the calm of a Zen monk",
  "as if mid-evil-monologue",
  "with the joy of someone who just won the lottery",
  "looking absolutely furious",
  "in a state of pure ecstasy",
  "with quiet dignity",
  "looking nostalgic and wistful",
  "with the energy of a motivational speaker",
];

const POSES = [
  "gripping the wheel with both hands",
  "leaning casually on the steering wheel with one arm",
  "standing up on the seat for a better view",
  "doing a one-handed wave at the camera",
  "mid-jump out of the seat in celebration",
  "lounging back like the tractor drives itself",
  "shifting gears with comical effort",
  "throwing both hands in the air in triumph",
  "leaning forward like a race-car driver",
  "drifting the tractor sideways through a turn",
  "pointing dramatically into the distance",
  "balancing on the seat in a yoga pose",
  "tipping their hat at the camera",
  "doing the dab",
  "throwing a peace sign with the free hand",
];

const CAMERA_ANGLES = [
  "low-angle shot looking up at the tractor",
  "bird's-eye view from directly above",
  "tight close-up on the monkey's face",
  "wide cinematic establishing shot",
  "Dutch-tilt diagonal angle for drama",
  "over-the-shoulder view from behind the monkey",
  "head-on front view from ground level",
  "side profile shot",
  "extreme close-up on the steering wheel and monkey's hands",
  "drone shot pulling away into the sky",
  "first-person POV from the driver's seat",
  "rear three-quarter angle showing exhaust smoke",
];

const TIMES_OF_DAY = [
  "at golden hour with long warm shadows",
  "at high noon with harsh midday light",
  "during the blue hour just after sunset",
  "under a starry midnight sky",
  "on an overcast grey morning",
  "during a thunderstorm with dramatic lightning",
  "at dawn with mist hanging low",
  "under a full harvest moon",
  "in heavy fog with shafts of light breaking through",
  "during a vibrant pink-and-orange sunset",
  "in pouring rain with puddles reflecting light",
  "under the aurora borealis",
  "during a solar eclipse",
];

const LIGHTING = [
  "with cinematic rim lighting",
  "lit by warm tungsten lamps",
  "with dramatic chiaroscuro contrast",
  "in soft diffused daylight",
  "with neon underglow lighting the scene",
  "backlit by a brilliant sunburst",
  "lit by flickering torchlight",
  "with cool moonlit blue tones",
  "with bounce light from a giant white reflector",
  "lit only by the tractor's headlights",
  "with volumetric god-rays slanting through dust",
  "bathed in green-screen alien glow",
];

function pickOne<T>(rng: () => number, arr: readonly T[]): T {
  const value = arr[Math.floor(rng() * arr.length)];
  if (value === undefined) {
    throw new Error("pickOne: empty array");
  }
  return value;
}

export interface PromptParts {
  readonly style: string;
  readonly tractor: string;
  readonly setting: string;
  readonly quirk: string;
  readonly mood: string;
  readonly pose: string;
  readonly cameraAngle: string;
  readonly timeOfDay: string;
  readonly lighting: string;
}

export function buildPromptParts(rng: () => number = Math.random): PromptParts {
  return {
    style: pickOne(rng, STYLES),
    tractor: pickOne(rng, TRACTORS),
    setting: pickOne(rng, SETTINGS),
    quirk: pickOne(rng, MONKEY_QUIRKS),
    mood: pickOne(rng, MOODS),
    pose: pickOne(rng, POSES),
    cameraAngle: pickOne(rng, CAMERA_ANGLES),
    timeOfDay: pickOne(rng, TIMES_OF_DAY),
    lighting: pickOne(rng, LIGHTING),
  };
}

export function renderPrompt(parts: PromptParts, userHint?: string): string {
  const base =
    `${parts.cameraAngle}. A ${parts.style} of a monkey driving a ${parts.tractor} ${parts.setting}, ${parts.timeOfDay}. ` +
    `The monkey is ${parts.quirk}, ${parts.pose}, ${parts.mood}. ` +
    `${parts.lighting}. High detail, clearly the monkey is the driver behind the wheel.`;
  if (userHint === undefined || userHint.length === 0) return base;
  return `${base} The user requested: "${userHint}" — incorporate this idea into the scene while keeping the monkey-driving-a-tractor concept clearly recognizable.`;
}
